### ISSUE TITLE
add SLiM dependency

### ISSUE THREAD

**Issue by grahamgower** [conda-forge/stdpopsim-feedstock#5]
```
$ conda search stdpopsim==0.1.2 --info
Loading channels: done
stdpopsim 0.1.2 py_0
--------------------
file name   : stdpopsim-0.1.2-py_0.tar.bz2
name        : stdpopsim
version     : 0.1.2
build       : py_0
build number: 0
size        : 71 KB
license     : GPLv3+
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/stdpopsim-0.1.2-py_0.tar.bz2
md5         : b34d58eba8a83e8ad4d9e796f6f1c47b
timestamp   : 2020-06-02 09:51:08 UTC
dependencies:
  - appdirs
  - attrs >=19.1.0
  - humanize
  - msprime >=0.7.1
  - pyslim >=0.401
  - python >=3.6
```

Probably not much point doing this until the next stdpopsim release, as the slim engine isn't so useful in 0.1.2.

**Comment by petrelharp** [comment]
`stdpopsim` is usable without SLiM, so arguably we should not require it as a dependency? It is easy to install, so maybe we should just include it, but on the other hand I think it takes a while to install, so this might slow down automated pipelines unnecessarily.

**Comment by petrelharp** [comment]
Ah: and also, people might have their own installations of SLiM?

**Comment by jeromekelleher** [comment]
Other than download time, I don't think it'll add much time to the install, so unless that's significant I'd vote for including it.

**Comment by petrelharp** [comment]
Doesn't seem to be, so go for it.
